### ISSUE TITLE
passwordView?.titleToRequestAuthentication does not update

### ISSUE THREAD

**Issue by zacgibson21** [mayckonx/MBSPasswordView#5]
I can't seem to get the title to change from "inform your password".

**Comment by mayckonx** [comment]
Can you share your setup? 

Did you do something like that?

```
        passwordView?.delegate = self
        passwordView?.start(enableBiometrics: false)
```

**Comment by zacgibson21** [comment]
I have the extension installed through cocoapods. Here is my viewDidLoad
function, everything works but the line does not update.

Am I missing something?

Thank you

    *override* *func* viewDidLoad() {

        *super*.viewDidLoad()

        *// Do any additional setup after loading the view.*

        print("Lock Screen View Controller Loaded")

        passwordView?.delegate = *self*

        passwordView?.titleToRequestAuthentication = "Ding Dong!"

        passwordView?.start(enableBiometrics: *false*)

        passwordView?.topView.backgroundColor = UIColor.white

        passwordView?.topView.dotColor = UIColor.black

        passwordView?.topView.labelColor = UIColor.black



    }

**Comment by mayckonx** [comment]
@zacgibson21 I got it. Actually, the `itleToRequestAuthentication` is related to the ID authentication. When you start with `passwordView?.start(enableBiometrics: true)` it will open a popup request the Touch/Face ID if the device support it.

Currently, the library doesn't have support to change it. You can open a pull request to make it works. We have the property on the topView called `lblPasswordRequest` that is responsible to set that title.
